name: TopPlayers
version: 1.0.3-DEVELOPMENT-SNAPSHOT
main: com.gmail.gogobebe2.topplayerss.TopPlayers
description: Can create signs that show the top player.
author: William Bryant (gogobebe2)
website: gogobebe2@gmail.com
permissions:
  topsign.create:
    default: op